# Generated by Django 4.1 on 2022-08-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loggerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='sub_till',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
