# Generated by Django 4.1 on 2022-08-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loggerapp', '0002_alter_profiles_sub_till'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=50)),
                ('redirect', models.CharField(default='https://www.google.com/', max_length=100)),
                ('screamer', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='Passes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True)),
                ('link', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Переход',
                'verbose_name_plural': 'Переходы',
            },
        ),
    ]
