# Generated by Django 4.1 on 2022-08-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loggerapp', '0003_links_passes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passes',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
