# Generated by Django 4.1 on 2022-08-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loggerapp', '0004_alter_passes_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
