# Generated by Django 4.1 on 2022-08-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loggerapp', '0006_passes_owner_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passes',
            name='owner_link',
            field=models.CharField(max_length=50),
        ),
    ]
