# Generated by Django 4.1 on 2022-08-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loggerapp', '0011_alter_profiles_sub_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='screamer',
        ),
        migrations.AddField(
            model_name='links',
            name='type',
            field=models.CharField(default='redirect', max_length=12),
        ),
        migrations.AddField(
            model_name='passes',
            name='fish',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
