# Generated by Django 4.1 on 2022-08-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loggerapp', '0012_remove_links_screamer_links_type_passes_fish'),
    ]

    operations = [
        migrations.AddField(
            model_name='passes',
            name='agent',
            field=models.CharField(default='not_loged', max_length=150),
        ),
    ]
